
spring:
  datasource:
    driver-class-name: org.h2.Driver
  http:
    log-request-details: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

logging:
  level:
    org:
      springframework:
        web: DEBUG